### ISSUE TITLE
Persistent bug with csvtools.missingKeywords()

### ISSUE THREAD

**Issue by pheuer** [uclahedp/uclahedp#2]
csvtools.missingKeywords() sometimes reports some missing keywords that definitely should be in the attribute dictionary. The behavior is erratic, and I haven't been able to trace down the cause. The misssing keywords generally seem to be ['motion_controller', 'motion_receptacle'].

An example error:

`Processing run: 23
Processing probe: ('tdiode', 'tdiode')
Running lapdToRaw
Traceback (most recent call last):
  File "/Users/dereks/Desktop/Research/Codes/Data/LAPD/Python/make_LAPD_Jan2019.py", line 75, in <module>
    rawfile =  lapdtools.lapdToRaw(run, probe[0], hdf_dir, csv_dir, rawfile, verbose=True)
  File "/Users/dereks/Documents/GitHub/uclahedp/uclahedp/lapdtools.py", line 65, in lapdToRaw
    csvtools.missingKeys(attrs, req_keys, fatal_error=True)
  File "/Users/dereks/Documents/GitHub/uclahedp/uclahedp/csvtools.py", line 391, in missingKeys
    raise ValueError("Missing columns in metadata attributes! The following keys were not found, and are required: " + str(missing_keys))
ValueError: Missing columns in metadata attributes! The following keys were not found, and are required: ['motion_controller', 'motion_receptacle']`

**Comment by pheuer** [comment]
This issue seems to have been solved, or otherwise disappeared? Closing for now, unless it comes up again.
