### ISSUE TITLE
Indexing error in bdotRawtoFull

### ISSUE THREAD

**Issue by dschaeffer17** [uclahedp/uclahedp#3]
Get following error when trying to process full bdot probe data for multiple runs (e.g. run 22):

Running bdotRawToFull
['brd1', 'brd2', 'brd3', 'chan1', 'chan2', 'chan3', 'xarea', 'yarea', 'zarea', 'xatten', 'yatten', 'zatten', 'gain', 'xpol', 'ypol', 'zpol', 'roll', 'probe_origin_x', 'probe_origin_y', 'probe_origin_z', 'dt', 'nturns', 'rot_center_x', 'rot_center_y', 'rot_center_z']
Loading tdiode array from file.
Opening destination HDF file
Creating 'data' group in destination file
Beginning processing data shot-by-shot.
100/174 done 01:34 remaining
Traceback (most recent call last):
  File "/Users/dereks/Desktop/Research/Codes/Data/LAPD/Python/make_LAPD_Jan2019.py", line 91, in <module>
    fullfile = bdot.bdotRawToFull(rawfile, fullfile, tdiode_hdf=tdiode_full, grid=True, verbose=True)
  File "/Users/dereks/Documents/GitHub/uclahedp/uclahedp/bdot.py", line 243, in bdotRawToFull
    destgrp['data'][:, xi, yi, zi, repi, 0] = bx
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/anaconda3/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 609, in __setitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/anaconda3/lib/python3.7/site-packages/h5py/_hl/selections.py", line 94, in select
    sel[args]
  File "/anaconda3/lib/python3.7/site-packages/h5py/_hl/selections.py", line 261, in __getitem__
    start, count, step, scalar = _handle_simple(self.shape,args)
  File "/anaconda3/lib/python3.7/site-packages/h5py/_hl/selections.py", line 451, in _handle_simple
    x,y,z = _translate_int(int(arg), length)
  File "/anaconda3/lib/python3.7/site-packages/h5py/_hl/selections.py", line 471, in _translate_int
    raise ValueError("Index (%s) out of range (0-%s)" % (exp, length-1))
ValueError: Index (3) out of range (0-2)

**Comment by pheuer** [comment]
This was fixed 2/12/19: I just forgot to close the issue here until now
