### ISSUE TITLE
DataView crashes if one of the displayed axes is not an array

### ISSUE THREAD

**Issue by dschaeffer17** [uclahedp/uclahedp#5]
If you select an axis that is not an array (i.e. only one element, perhaps from averaging), DataView crashes.  See error log below:

Traceback (most recent call last):
  File "/Users/dereks/Documents/GitHub/dataview/dataview/dataview.py", line 434, in updateAxesFieldsAction
    self.makePlot()
  File "/Users/dereks/Documents/GitHub/dataview/dataview/dataview.py", line 516, in makePlot
    self.plot2D()
  File "/Users/dereks/Documents/GitHub/dataview/dataview/dataview.py", line 682, in plot2D
    cs = self.canvas_ax.contourf(hax, vax, data, levels, cmap=colormap)
  File "/anaconda3/lib/python3.7/site-packages/matplotlib/__init__.py", line 1810, in inner
    return func(ax, *args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 6239, in contourf
    contours = mcontour.QuadContourSet(self, *args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/matplotlib/contour.py", line 887, in __init__
    kwargs = self._process_args(*args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/matplotlib/contour.py", line 1493, in _process_args
    x, y, z = self._contour_args(args, kwargs)
  File "/anaconda3/lib/python3.7/site-packages/matplotlib/contour.py", line 1551, in _contour_args
    x, y, z = self._check_xyz(args[:3], kwargs)
  File "/anaconda3/lib/python3.7/site-packages/matplotlib/contour.py", line 1585, in _check_xyz
    raise TypeError("Input z must be a 2D array.")
TypeError: Input z must be a 2D array.
Abort trap: 6

**Comment by dschaeffer17** [comment]
Just realized this belongs in the other repository.  Copying over and closing this one.
